services:
  db:
    image: postgres:16
    container_name: tgpay-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tgpay
    ports:
      - "5432:5432"
    volumes:
      - tgpay_pg:/var/lib/postgresql/data

volumes:
  tgpay_pg: